apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
<<<<<<< HEAD
      rolearn: arn:aws:iam::366858220625:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-18S6363XBCIJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::366858220625:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-08T08:33:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1727"
  uid: d77c8ebe-a22e-49e4-be73-92174374b482
=======
      rolearn: arn:aws:iam::971420046292:role/eksctl-myproj-jwt-api-nodegroup-n-NodeInstanceRole-CJKHUR25370Z
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::971420046292:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T22:51:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1609"
  uid: b2d18232-4279-4d75-9754-f963d2c61c7a
>>>>>>> e536ba06b5287397b28c5d5e377e9c417aed1814
